config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :user
  get 'dashboard', to: 'pages#dashboard', as: :dashboard
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats do
    resources :bookings, only: [:new, :create]
    resources :reviews, only: [:index]
  end
  resources :bookings do
    resources :reviews, only: [:index, :new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :flat
  validates :checkin_date, presence: true
  validates :checkout_date, presence: true
  validate :no_booking_overlap
  has_one :review


def no_booking_overlap
  if (Booking.where("(? BETWEEN checkin_date AND checkout_date OR ? BETWEEN checkin_date AND checkout_date) AND user_id = ? AND flat_id = ?", self.checkin_date, self.checkout_date, self.user_id, self.flat_id).any?)
     errors.add(:checkout_date, 'it overlaps another reservation')
  end
end

end

app/models/flat.rb
class Flat < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :user
  has_many :bookings
  has_many :reviews, through: :bookings
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  # validates :name, presence: true
  # validates :description, presence: true
  # validates :daily_price, presence: true
  # validates :address, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  validates :rating, presence: true
  validates :description, presence: true
  validates_inclusion_of :rating, :in => [0, 1, 2, 3, 4, 5]
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  has_many :flats
  has_many :bookings

  # validates_format_of :email,:with => Devise::email_regexp
  # validates :email, presence: true, uniqueness: true
  # validates :password, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :gender, presence: true
  validates :phone_number, presence: true
  validates :birthdate, presence: true

  validates :photo, presence: true
   # validates :owner, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :gender, :phone_number, :birthdate, :photo, :owner])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :gender, :phone_number, :birthdate, :photo, :owner])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
   before_action :set_booking, only: [:show, :destroy]

   def index
    @bookings = policy_scope(Booking).where(user_id: current_user)
    @flats = policy_scope(Flat).where(flat_id: @user.bookings[0][:flat_id])
   end

  def new
    @flat = Flat.find(params[:flat_id])
    @booking = Booking.new
    authorize @booking
  end

  def create
    @flat = Flat.find(params[:flat_id])
    @booking = Booking.new(booking_params)
    @booking.flat_id = params[:flat_id]
    @booking.user_id = current_user.id
    authorize @booking
    if @booking.save
      redirect_to @flat
    else
      render :new
    end
  end

  # def destroy
  #   @booking = Booking.find(params[:id])
  #   @booking.destroy
  #   redirect_to flat_path(@booking.flat)
  # end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:checkin_date, :checkout_date)
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    if params[:query].present? && params[:query1].present? && params[:query2].present?
      @bookings = Booking.where(flat: @flat)
      @flats = policy_scope(Flat.geocoded).joins(:bookings).where('flats.address ILIKE ? AND bookings.checkin_date > ? AND bookings.checkout_date < ?', "%#{params[:query]}%", "%#{params[:query1]}%", "%#{params[:query2]}%") #returns flats with coordinates
      @markers = @flats.map do |flat|
        {
          lat: flat.latitude,
          lng: flat.longitude
        }
      end
      else
      @flats = policy_scope(Flat.geocoded)
      @markers = @flats.map do |flat|
        {
          lat: flat.latitude,
          lng: flat.longitude
        }
      end
    end
  end


 def create
  @flat = Flat.new(flat_params)
  authorize @flat
  @flat.user_id = current_user.id
  if @flat.save
    redirect_to @flat
  else
    render 'new'
  end
end


def show
  @flat = Flat.find(params[:id])
  @bookings = Booking.where(flat: @flat)
  @review = Review.where(booking: @booking)
  authorize @flat
end

def new
  @flat = Flat.new
  authorize @flat
end




def edit
  @flat = Flat.find(params[:id])
  authorize @flat
end


def update
  @flat = Flat.find(params[:id])
  @flat.update(flat_params)
  authorize @flat
  if @flat.save
    redirect_to @flat
  else
    render 'new'

  end
end

private
def flat_params
  params.require(:flat).permit(:name, :description, :daily_price, :address, :features, :photo, :photo_cache)
end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def dashboard
    @user = current_user
  end


  def destroy
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
    redirect_to root_url
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @flat = Flat.find(params[:flat_id])
    @booking = Booking.find_by(flat_id: @flat)
    @reviews = Review.where(booking_id: @booking)
  end

  def new
    @booking = Booking.find(params[:booking_id])
    @review = Review.new
    authorize @review
  end

  def create
    @booking = Booking.find(params[:booking_id])
    @review = Review.new(review_params)
    authorize @review
    @review.booking = @booking
    @review.rating = review_params["rating"].to_i
    if @review.save
      redirect_to flat_path(@booking.flat)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :description)
  end

  def set_booking
    @booking = Booking.find(params[:booking_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<% @bookings.each do |booking| %>
<%= booking.flat.name %>
<%= booking.user.first_name %>
<% end %>

app/views/bookings/new.html.erb
<div class="container">

<body style="background-image: url('https://images.unsplash.com/photo-1521464302861-ce943915d1c3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1951&q=80');">
<h2 class="text-center py 10" style="color: white;">Select your dates</h2>

<div class="modal-card mx-auto text-center" style="width: 600px; padding: 20px; margin: 20px; text-decoration-color: black">

<%= simple_form_for [@flat, @booking] do |f| %>
  <%= f.input :checkin_date, as: :string, required: false, input_html: {id: "range_start" } %>
  <%= f.input :checkout_date, as: :string, required: false, input_html: {id: "range_end" } %>
  <%= f.button :submit %>
<% end %>
<%= link_to "Back", dashboard_path, class: 'button' %>
</div>

</body>

app/views/flats/edit.html.erb
<body style="background-image: url('https://images.unsplash.com/photo-1521464302861-ce943915d1c3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1951&q=80');">
<h2 class="text-center py 10" style="color: white;">Edit your flat</h2>

<div class="modal-card mx-auto text-center" style="width: 600px; padding: 20px; margin: 20px; text-decoration-color: black">
<%= simple_form_for @flat do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :address %>
  <%= f.input :daily_price %>
  <%= f.input :features %>
  <%= f.button :submit %>
<div class="button text-center" style="margin-top: 30px">
<%= link_to "Back", dashboard_path %>
<% end %>
</div>
</div>
</body>

app/views/flats/index.html.erb
<nav class="navbar navbar-expand-lg nav-background">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://image.flaticon.com/icons/svg/2111/2111320.svg" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
      </li>
    </ul>
     <%= link_to "Became a host", new_flat_path , class: "nav-link-1" %>
    <%= link_to "Log-out", destroy_user_session_path , method: :delete, class: "nav-link-1" %>
    <%= link_to dashboard_path do %>
    <%= cl_image_tag current_user.photo, class: "avatar avatar-bordered" %>
    <% end %>

  </div>
</nav>

<div class="info">
  <h6><i class="fas fa-trophy fa-lg" style="color:#F6C667;"></i> Over 340,000 guest reviews for places to stay in Buenos Aires, with an average of 4.8 out of 5 stars.</h6>
<h3>300+ places to stay</h3>
</div>

<div class="display-content pl-3">
<div class="card" style="max-width: 800px;">
  <% @flats.each do |flat| %>
  <div class="bor row no-gutters py-4 px-2 align-items-center">
    <div class="col-md-6">
      <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://source.unsplash.com/900x900/?apartment" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="https://source.unsplash.com/900x900/?apartment" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="https://source.unsplash.com/900x900/?apartment" class="d-block w-100" alt="...">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
    </div>
    <div class="col-md-6">
      <div class="card-body">
        <h5 class="card-title"><%=flat.name %></h5>
        <p class="card-text"><%=flat.description %></p>
        <p class="card-text">Price: <%=flat.daily_price %>$</p>
        <p class="card-text"><%=flat.features %><i class="fas fa-wifi"></i> Wi-Fi</p>
        <p><i class="fas fa-utensils"></i> Kitchen</p>
        <p><i class="fas fa-tv"></i> TV</p>
        <p class="card-text"><small class="text-muted"><%=flat.address%></small></p>
        <%= link_to "View", flat_path(flat), class: 'button' %>

      </div>
    </div>
  </div>
  <% end %>
</div>
<div
  id="map"
  style="width: 80%;
  height: 1000px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>


</div>

app/views/flats/new.html.erb
<body style="background-image: url('https://images.unsplash.com/photo-1521464302861-ce943915d1c3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1951&q=80');">
<h2 class="text-center py 10" style="color: white;">Add your own flat</h2>

<div class="modal-card mx-auto text-center" style="width: 600px; padding: 20px; margin: 20px; text-decoration-color: black">
<%= simple_form_for @flat do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :address %>
  <%= f.input :daily_price %>
  <%= f.input :features %>
  <%= f.button :submit %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
<% end %>
<%= link_to "Back", flats_path, class: 'btn btn-light mx-2 justify-content-center text-center' %>
</div>
</body>

app/views/flats/show.html.erb
<nav class="navbar navbar-expand-lg nav-background">



  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://image.flaticon.com/icons/svg/2111/2111320.svg" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
      </li>
    </ul>
     <%= link_to "Became a host", new_flat_path , class: "nav-link-1" %>
    <%= link_to "Log-out", destroy_user_session_path , method: :delete, class: "nav-link-1" %>
        <%= link_to dashboard_path do %>
    <%= cl_image_tag current_user.photo , class: "avatar avatar-bordered"%>
  <% end %>
  </div>
</nav>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path @flat.photo %>)">
  <div class="container">
    <h1><strong> <%= @flat.name %> </strong></h1>
    <p><%=@flat.description %></p>
    <%= link_to "Book this apartment", new_flat_booking_path(@flat), class: 'button-white' %>
  </div>
</div>
<div class="card my-2 d-flex justify-content-center text-center mx-4">
  <h1 class="text-color"><strong>Reviews for this apartment</strong></h1>
  <p><% @flat.bookings.each do |booking| %>
    <p> <% if !booking.review.nil? %>
      <% booking.review.rating.times do %>
      <i class="fa fa-star" aria-hidden="true"> </i>
      <% end %>
      "<%= a = booking.review.description %>" </p>
      <% end %>
      <% end %>
    </div>
    <div class="card my-2 d-flex justify-content-center text-center mx-4">
      <h2>Features</h2>
      <p><%= @flat.features %></p>
    </div>
    <div class="container my-2 d-flex justify-content-center">
      <%= link_to "Back", flats_path, class: 'button' %>
    </div>

    <footer class="footer-show">
      <div class="row">
        <div class="col-6 col-md text-center">
         <h5>Airbnb  <i class="fas fa-home"></i></h5>
          <ul class="list-unstyled text-small">
            <li><a class="" href="#">Opportunità di lavoro</a></li>
            <li><a class="" href="#">News</a></li>
            <li><a class="" href="#">Condizioni</a></li>
            <li><a class="" href="#">Aiuto</a></li>
            <li><a class="" href="#">Diversità e appartenenza</a></li>
            <li><a class="" href="#">Informazioni di contatto</a></li>
          </ul>
        </div>
        <div class="col-6 col-md text-center">
         <h5>Scopri  <i class="fas fa-search-location"></i></h5>
          <ul class="list-unstyled text-small" id="footer-column">
            <li><a class="" href="#">Affidabilità e sicurezza</a></li>
            <li><a class="" href="#">Attività</a></li>
            <li><a class="" href="#">Cittadino Airbnb</a></li>
            <li><a class="" href="#">Viaggi di lavoro</a></li>
          </ul>
        </div>
        <div class="col-6 col-md text-center" id="footer-column">
          <h5>Ospita  <i class="fas fa-bed"></i></h5>
          <ul class="list-unstyled text-small">
            <li><a class="" href="#">Perchè affittare</a></li>
            <li><a class="" href="#">Ospita</a></li>
            <li><a class="" href="#">Ospitare responsabilmente</a></li>
            <li><a class="" href="#">Offri un'esperienza</a></li>
          </ul>
        </div>
        <div class="col-6 col-md text-center" id="footer-column">
          <h5>Rules  <i class="fas fa-file-alt"></i></h5>
          <ul class="list-unstyled text-small" >
            <li><a class="" href="#">Termini</a></li>
            <li><a class="" href="#">Privacy</a></li>
            <li><a class="" href="#">Mappa del sito</a></li>
          </ul>
        </div>
      </div>
    </footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>TODO</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>

  <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
  <%#= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>
</body>
</html>

app/views/pages/dashboard.html.erb
<nav class="navbar navbar-expand-lg nav-background">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://image.flaticon.com/icons/svg/2111/2111320.svg" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
      </li>
    </ul>
     <%= link_to "Became a host", new_flat_path , class: "nav-link-1" %>
    <%= link_to "Log-out", destroy_user_session_path , method: :delete, class: "nav-link-1" %>
    <%= cl_image_tag current_user.photo , class: "avatar avatar-bordered"%>

  </div>
</nav>
<div>

<div class="card-body card my-2 d-flex justify-content-center text-center mx-4">
  <h1 class="text-color">Manage Your Flats</h1>
<div class="card-trip">
  <img src="https://source.unsplash.com/900x900/?apartment">
  <div class="card-trip-infos">
    <div>
      <p><%@user.flats.each do |flat| %></p>
      <h2 class="text-color"><%= flat.name %> </h2>
      <p><%= flat.description %></p>
      <p><%= flat.address %></p>
    </div>
  <%= link_to "edit flat", edit_flat_path(flat), class: 'button' %>
       <% end %>
  </div>
</div>
</div>


  <div class="card-body card my-2 d-flex justify-content-center text-center mx-4">
  <h1 class="text-color">Your Bookings</h1>
  <div class="card-trip">
  <%@user.bookings.each do |booking| %>
  <h4><%= booking.flat.name %></h4>
  <h5><%= booking.flat.address %></h5>
  <p>Check-in Date <%= booking.checkin_date %> </p>
  <p>Check-out Date <%= booking.checkout_date %> </p>
  <%= link_to "New Review for this booking", new_booking_review_path(booking), class: 'button' %>
  <% end %>
  <br>
</div>
</div>

<div class="card-body justify-content-center text-center">
<%= link_to "Back", flats_path, class: 'button' %>
</div>


    <footer class="footer-show">
      <div class="row">
        <div class="col-6 col-md">
         <h5>Airbnb  <i class="fas fa-home"></i></h5>
          <ul class="list-unstyled text-small">
            <li><a class="" href="#">Opportunità di lavoro</a></li>
            <li><a class="" href="#">News</a></li>
            <li><a class="" href="#">Condizioni</a></li>
            <li><a class="" href="#">Aiuto</a></li>
            <li><a class="" href="#">Diversità e appartenenza</a></li>
            <li><a class="" href="#">Informazioni di contatto</a></li>
          </ul>
        </div>
        <div class="col-6 col-md">
         <h5>Scopri  <i class="fas fa-search-location"></i></h5>
          <ul class="list-unstyled text-small" id="footer-column">
            <li><a class="" href="#">Affidabilità e sicurezza</a></li>
            <li><a class="" href="#">Attività</a></li>
            <li><a class="" href="#">Cittadino Airbnb</a></li>
            <li><a class="" href="#">Viaggi di lavoro</a></li>
          </ul>
        </div>
        <div class="col-6 col-md" id="footer-column">
          <h5>Ospita  <i class="fas fa-bed"></i></h5>
          <ul class="list-unstyled text-small">
            <li><a class="" href="#">Perchè affittare</a></li>
            <li><a class="" href="#">Ospita</a></li>
            <li><a class="" href="#">Ospitare responsabilmente</a></li>
            <li><a class="" href="#">Offri un'esperienza</a></li>
          </ul>
        </div>
        <div class="col-6 col-md" id="footer-column">
          <h5>Rules  <i class="fas fa-file-alt"></i></h5>
          <ul class="list-unstyled text-small" >
            <li><a class="" href="#">Termini</a></li>
            <li><a class="" href="#">Privacy</a></li>
            <li><a class="" href="#">Mappa del sito</a></li>
          </ul>
        </div>
      </div>
    </footer>

app/views/pages/home.html.erb
<div class="content-container">

  <% if user_signed_in?  %>

<nav class="navbar navbar-expand-lg navbar-light bg-transparent">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://image.flaticon.com/icons/svg/2111/2111320.svg" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
      </li>
      <li class="nav-item">
      </li>
      <li class="nav-item">
      </li>
    </ul>
    <%= link_to "Became a host", new_flat_path , class: "nav-link" %>
    <%= link_to "Log-out", destroy_user_session_path , method: :delete, class: "nav-link" %>
    <%= link_to dashboard_path do %>
    <%= cl_image_tag current_user.photo , class: "avatar avatar-bordered"%>
    <% end %>
  </div>
</nav>

<% else %>

<nav class="navbar navbar-expand-lg navbar-light bg-transparent">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://image.flaticon.com/icons/svg/2111/2111320.svg" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
      </li>
      <li class="nav-item">
      </li>
      <li class="nav-item">
      </li>
    </ul>
    <%= link_to "Sign-up", new_user_registration_path , class: "nav-link" %>
    <%= link_to "Login", new_user_session_path , class: "nav-link" %>
  </div>
</nav>
<% end %>





  <div class="container-home">
    <div class="container_form" >
      <div class="text mb-3">
        <h1>Book <span class="differentcolor">Unique</span> Experience to <span class="differentcolor">live.</span></h1>
      </div>
  <%= form_tag flats_path, class: "form-inline justify-content-center homepage-form", method: :get do %>
  <%= text_field_tag :query,
  params[:query],
  class: "form mr-2 ",
    placeholder: "Find a flat"
    %>

    <%= date_field_tag :query1,
    params[:query1],
    class: "form mr-2",
      id: "",
      placeholder: "checkin_date"
      %>
    <%= date_field_tag :query2,
    params[:query2],
    class: "form mr-2",
      id: "",
      placeholder: "checkout_date"
      %>
      <%= text_field_tag :query3,
    params[:query3],
    class: "form mr-2",
      id: "",
      placeholder: "ospiti"
      %>
        <span><%= submit_tag "Search", class: "search-button" %></span>
      </div>
    </div>
  </div>
        <% end %>

      </div>

app/views/reviews/index.html.erb
<div>
<% @reviews.each do |review| %>
<h1><%=review.rating %></h1>
<p><%=review.description %></p>
<br>
<% end %>
</div>

app/views/reviews/new.html.erb
<body style="background-image: url('https://images.unsplash.com/photo-1521464302861-ce943915d1c3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1951&q=80');">
<h2 class="text-center py 10" style="color: white;">Add a Review</h2>

<div class="modal-card mx-auto text-center" style="width: 600px; padding: 20px; margin: 20px; text-decoration-color: black">
<%= simple_form_for [@booking, @review] do |f| %>
  <%= f.input :rating %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>
<div style="margin-top: 30px; margin-bottom: 30px">
<%= link_to "Back", dashboard_path, class: 'button' %>
</div>
</div>
</body>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to('Logout', destroy_user_session_path, method: :delete) %>

            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>